CREATE SCHEMA IF NOT EXISTS security;

CREATE TABLE IF NOT EXISTS security.users (
  USERNAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  ENABLED boolean NOT NULL,
  ACCOUNT_NON_EXPIRED boolean,
  ACCOUNT_NON_LOCKED  boolean, 
  PRIMARY KEY (username));
	
CREATE TABLE IF NOT EXISTS security.user_authorities (
  ID TEXT NOT NULL,
  USERNAME TEXT NOT NULL,
  AUTHORITY TEXT NOT NULL,
  UNIQUE (USERNAME, AUTHORITY),
  CONSTRAINT fk_authorities_users FOREIGN KEY (USERNAME) REFERENCES security.users (USERNAME));
