-- Security
CREATE SCHEMA IF NOT EXISTS security;

CREATE TABLE IF NOT EXISTS security.users (
  USERNAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  ENABLED boolean NOT NULL,
  ACCOUNT_NON_EXPIRED boolean,
  ACCOUNT_NON_LOCKED  boolean, 
  PRIMARY KEY (USERNAME));
	
CREATE TABLE IF NOT EXISTS security.user_authorities (
  ID TEXT NOT NULL,
  USERNAME TEXT NOT NULL,
  AUTHORITY TEXT NOT NULL,
  UNIQUE (USERNAME, AUTHORITY),
  CONSTRAINT fk_authorities_users FOREIGN KEY (USERNAME) REFERENCES security.users (USERNAME));

  -- Company
  CREATE SCHEMA IF NOT EXISTS company;
  
  CREATE SEQUENCE company.company_seq INCREMENT 1;
  
  CREATE TABLE IF NOT EXISTS company.company (
  ID TEXT NOT NULL DEFAULT NEXTVAL('company.company_seq')::text,
  NAME TEXT NOT NULL,
  PARENT TEXT,
  PRIMARY KEY (ID),
  CONSTRAINT fk_company_parent FOREIGN KEY (PARENT) REFERENCES company.company (ID));
  